import type { PresetPackage } from "@/types/preset";

export const PRESET_PACKAGES: PresetPackage[] = [
  {
    id: "city-girl",
    label: "City Girl",
    labelZh: "都市丽人",
    description: "Rooftop vibes with influencer aesthetic",
    sceneId: "rooftop-dusk",
    styleId: "influencer",
    outfitId: "casual-chic",
    moodId: "confident",
  },
  {
    id: "sakura-dream",
    label: "Sakura Dream",
    labelZh: "樱花梦",
    description: "Cherry blossoms with Xiaohongshu style",
    sceneId: "cherry-blossom",
    styleId: "xiaohongshu",
    outfitId: "bohemian",
    moodId: "dreamy",
  },
  {
    id: "magazine-cover",
    label: "Magazine Cover",
    labelZh: "杂志封面",
    description: "Studio editorial, high fashion",
    sceneId: "white-studio",
    styleId: "editorial",
    outfitId: "evening",
    moodId: "elegant",
  },
  {
    id: "cafe-date",
    label: "Cafe Date",
    labelZh: "咖啡时光",
    description: "Sunlit cafe with natural vibes",
    sceneId: "sunlit-cafe",
    styleId: "natural",
    outfitId: "casual-chic",
    moodId: "playful",
  },
  {
    id: "travel-diary",
    label: "Travel Diary",
    labelZh: "旅行日记",
    description: "Santorini with Xiaohongshu aesthetic",
    sceneId: "santorini",
    styleId: "xiaohongshu",
    outfitId: "minimal",
    moodId: "joyful",
  },
  {
    id: "film-noir",
    label: "Film Noir",
    labelZh: "电影胶片",
    description: "Neon streets with cinematic mood",
    sceneId: "neon-street",
    styleId: "cinematic",
    outfitId: "streetwear",
    moodId: "mysterious",
  },
  {
    id: "vintage-story",
    label: "Vintage Story",
    labelZh: "复古故事",
    description: "Bookstore with retro film feel",
    sceneId: "vintage-bookstore",
    styleId: "retro",
    outfitId: "casual-chic",
    moodId: "casual",
  },
  {
    id: "cool-street",
    label: "Cool Street",
    labelZh: "酷飒街头",
    description: "Urban plaza with streetwear edge",
    sceneId: "modern-plaza",
    styleId: "influencer",
    outfitId: "streetwear",
    moodId: "cool",
  },
];
